server:
  port: 8081
spring:
  application:
    name: reactivecommonssubscriber
  rabbitmq:
    #host: 8.8.8.1
    host: 127.0.0.1
    #port: 5729
    port: 5672
    username: guest
    password: guest